Dev
Anastasia-Nikitina/Big-Integer pull request #1
Opened 2021-10-23 10:20 UTC by Anastasia-Nikitina

2021-10-23 11:10 UTC, gsvgit requested changes
Посмотрите, пожалуйста, внимательно на свой код. Что-то много странного происходит.

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +           int string.[i] - 48
А почему 48 ?

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +let comparision (x: MyList<int>) (y: MyList<int>) = // выводит true если первое число больше второго
1. Тогда уж ```compare```
2. Нормальный compare возвращает одно из трёх значений: больше, меньше, равно.

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +            if a > b then true
Гениально!

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +            if (Length x > Length y) then true
Тоже отличный код!

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +               if a = b
Отлично

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +                            let k = selection (removeZeros a) b
Форматирование.

2021-10-23 11:10 UTC, gsvgit commented on src/BigInteger/Library.fs
> +    /// let sample = hello "Chris"
Что это?

2021-10-23 11:15 UTC, Anastasia-Nikitina commented on src/BigInteger/BigInt.fs
> +let comparision (x: MyList<int>) (y: MyList<int>) = // выводит true если первое число больше второго
решила, что для равенства лучше написать отдельную функцию, так проще вроде

2021-10-23 11:24 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +let comparision (x: MyList<int>) (y: MyList<int>) = // выводит true если первое число больше второго
Так дело не в равенстве как отдельной функции. Если Вы посмотрите на современные языки программирования, там тоже как правило есть ```equal``` и  ```compare``` отдельно. Дело в том, что у comapre  три возможных значения, а не два.

2021-10-23 11:38 UTC, Anastasia-Nikitina commented on src/BigInteger/BigInt.fs
> +           int string.[i] - 48
это код нуля в ASCII

2021-10-23 11:42 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +           int string.[i] - 48
И? Вроде ```int "1" ```  возвращает 1. Зачем что-то вычитать?

2021-10-25 08:33 UTC, gsvgit requested changes

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +   SystemToMyList (List.rev (MyListToSystem x))
А почему часть функция с большой буквы, а часть с маленькой?

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +let reverse (x: MyList<int>) =
И почему функции, относящиеся к спискам, живут в длиных числах?

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +    let rec go (a: MyList<int>) (b: MyList<int>) =
И это, кажется, про списки.

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/BigInt.fs
> +    SystemToMyList ((MyListToSystem a).[x1..x2])
И это про списки.

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/Lexer.fsl
> +let number = sign + ('0' ' ' | digits)
А откуда в числах пробелы?

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/Lexer.fsl
> +| number		{ Parser.NUM((LexBuffer<_>.LexemeString lexbuf).Trim() |> BigInt.StringToNWS) }
И тримы где-то такие я уже видел.... Коллективный разум?

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/Library.fs
> +    /// let sample = hello "Chris"
И всё же. Что это?

2021-10-25 08:33 UTC, gsvgit commented on src/BigInteger/Parser.fsy
> +    | NUM {failwith "parse error"}
М.... Почитайте, что я Елене по этому поводу рассказал.

2021-10-25 08:33 UTC, gsvgit commented on tests/BigInteger.UnitTests/UnitTest1.fs
> +            let a1 = genRandomBigInteger 30
А почему у Вас проперти тесты не пользуются своими аргументами?

2021-10-25 14:57 UTC, Anastasia-Nikitina commented on tests/BigInteger.UnitTests/UnitTest1.fs
> +            let a1 = genRandomBigInteger 30
а что здесь передавать в качестве аргументов? Размер числа? Тогда проблемы с тем, что может сгенерировать отрицательное или 0

2021-10-25 15:01 UTC, gsvgit commented
Подумайте. Проблему с отрицательными решает uint64. Да и отрицательные
числа как таковые у Вас поддерживаются

On Mon, Oct 25, 2021, 5:57 PM Anastasia-Nikitina ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/BigInteger.UnitTests/UnitTest1.fs
> <https://github.com/Anastasia-Nikitina/Big-Integer/pull/1#discussion_r735687614>
> :
>
> > +            let a1 = SystemToMyList(genRandomList 10)
>
> +            let a2 = SystemToMyList (genRandomList 3)
>
> +            let (res1, res2) = addZeros a1 a2
>
> +            Expect.equal (Length res1) (Length res2) ""
>
> +         testCase "Test for removeZeros" <| fun _ ->
>
> +             let a1 = Cons(1, Cons(5, Single 3))
>
> +             let a2 = Cons(0, Cons(0, Cons(0, Cons(1, Cons(5, Single 3)))))
>
> +             let a3 = Cons(1, Cons(5, Cons(3, Cons(0, Cons(0, Single 0)))))
>
> +             Expect.equal (removeZeros a2) a1 ""
>
> +        ]
>
> +
>
> +[<Tests>]
>
> +let Tests2 =
>
> +    testList "Tests for BigInt"
>
> +        [testProperty "Test for sum" <| fun _ ->
>
> +            let a1 = genRandomBigInteger 30
>
>
> а что здесь передавать в качестве аргументов? Размер числа? Тогда проблемы
> с тем, что может сгенерировать отрицательное или 0
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Nikitina/Big-Integer/pull/1#discussion_r735687614>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQB5IUIBRZK3MCTHOIDUIVV5ZANCNFSM5GSDT4EA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-26 19:34 UTC, Anastasia-Nikitina commented on src/BigInteger/Library.fs
> +    /// let sample = hello "Chris"
это пример из шаблона WayPoint, забыла удалить:)

2021-10-28 09:10 UTC, gsvgit requested changes

2021-10-28 09:10 UTC, gsvgit commented on tests/BigInteger.UnitTests/UnitTest1.fs
> +             Expect.isTrue (isEqualNWS res exp)
Удивительный тест. При умножении достатьчно больших чисел должно происходить переполнение.

2021-10-28 09:10 UTC, gsvgit commented on tests/BigInteger.UnitTests/UnitTest1.fs
> +         testProperty "Test for mult" <| fun _ ->
А такие тесты всё ещё выглядят странно.

2021-10-28 09:10 UTC, gsvgit commented on src/BigInteger/Program.fs
> +            printfn "%s" pD.["print"]
Магическая константа, которую Вы, вроде, пытались сделать менее магической.

2021-10-29 13:36 UTC, Anastasia-Nikitina commented on tests/BigInteger.UnitTests/UnitTest1.fs
> +             Expect.isTrue (isEqualNWS res exp)
Ну, я несколько раз запускала, переполнения не происходило. Но в принципе, могу брать не само число,  а его остаток от деления, например на 10000

2021-10-29 16:17 UTC, gsvgit commented
Лучше уже длинной арифметикой готовой пользоваться как эталоном.
Regards,
Semyon Grigorev.


пт, 29 окт. 2021 г. в 16:36, Anastasia-Nikitina ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/BigInteger.UnitTests/UnitTest1.fs
> <https://github.com/Anastasia-Nikitina/Big-Integer/pull/1#discussion_r739239590>
> :
>
> > +            let x1 = systemToMyBigInt (BigInteger x)
>
> +            let sb = toBin x1
>
> +            Expect.isTrue (isEqualNWS (systemToMyBigInt s) sb)
>
> +        ]
>
> +
>
> +[<Tests>]
>
> +let Tests3 =
>
> +    testList "Test for BigInt. Int64"
>
> +         [testProperty "Test for sum" <| fun (a: int64, b: int64) ->
>
> +             let res = addition (stringToNWS (string a)) (stringToNWS (string b))
>
> +             let exp = stringToNWS (string (a + b))
>
> +             Expect.isTrue (isEqualNWS res exp)
>
> +          testProperty "Test for mult" <| fun (a: int64, b: int64) ->
>
> +             let res = multiplication (stringToNWS (string a)) (stringToNWS (string b))
>
> +             let exp = stringToNWS (string (a * b))
>
> +             Expect.isTrue (isEqualNWS res exp)
>
>
> Ну, я несколько раз запускала, переполнения не происходило. Но в принципе,
> могу брать не само число, а его остаток от деления, например на 10000
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Nikitina/Big-Integer/pull/1#discussion_r739239590>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQB4G4T47WAYV2IUPZ3UJKPNBANCNFSM5GSDT4EA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-02 08:23 UTC, gsvgit approved these changes

2021-11-04 11:24 UTC, merged